"""Compatibility facade for the former ``_rules.py`` module."""

from __future__ import annotations

import sys

__all__ = [
    "first_significant_line",
    "is_full_module_candidate",
    "line_count",
    "looks_like_indented_fragment",
    "parse_health_failure",
    "parse_strict",
    "parsed_classes",
    "parsed_functions",
    "parsed_nodes",
    "python_ast_rule_is_disabled",
    "resolve_python_path",
    "PythonModuleSizeRule",
    "ModuleSizeFinding",
    "OVERSIZED_SPLIT_PLANS",
    "dedupe_sources",
    "is_authored_python_path",
    "is_line_count_camouflage",
    "module_split_scenario",
    "oversized_module_split_guidance",
    "post_python_structural_sources",
    "pre_python_camouflage_sources",
    "pre_python_structural_sources",
    "project_multiedit_sources",
    "project_replacement",
    "project_top_level_edit",
    "python_structural_sources",
    "read_python_source",
    "PythonAstHealthRule",
    "PythonBroadExceptLoggerRule",
    "PythonSilentExceptRule",
    "is_broad_exception",
    "is_empty_default_return",
    "is_logger_call",
    "BOUNDARY_LOG_METHODS",
    "BOUNDARY_LOG_NAMES",
    "BoundaryFunction",
    "EVENT_CALL_NAMES",
    "EVENT_NAME_MARKERS",
    "EVENT_PATH_PARTS",
    "HTTP_BOUNDARY_METHODS",
    "PACKAGE_BOUNDARY_CLASS_SUFFIXES",
    "PACKAGE_BOUNDARY_NAME_PARTS",
    "PACKAGE_BOUNDARY_PATH_PARTS",
    "attribute_chain_parts",
    "boundary_kind_for_function",
    "called_name",
    "class_name_has_package_boundary_signal",
    "contains_event_boundary_call",
    "contains_package_boundary_call",
    "function_name_has_event_signal",
    "has_boundary_log_call",
    "is_test_module_path",
    "iter_public_boundary_functions",
    "path_parts",
    "PythonBoundaryLoggingRule",
    "PythonDeepNestingRule",
    "PythonLongLineRule",
    "PythonLongMethodRule",
    "PythonLongParameterRule",
    "PythonFeatureEnvyRule",
    "PythonGodClassRule",
    "PythonThinWrapperRule",
    "is_exempt_cast_wrapper",
    "is_exempt_test_helper_wrapper",
    "is_test_helper_path",
    "is_wrapper_candidate",
    "thin_wrapper_attribute_name",
    "thin_wrapper_call_root_name",
    "thin_wrapper_call_target_name",
    "thin_wrapper_extract_single_call",
    "thin_wrapper_has_self_or_cls_receiver",
    "PythonCyclomaticComplexityRule",
    "PythonDeadCodeRule",
    "CC_BRANCH_TYPES",
    "PythonFlatFileSiblingsRule",
    "FlatSiblingFindingInput",
    "flat_sibling_patch_added_and_removed_paths",
    "flat_sibling_patch_blob",
    "flat_sibling_projected_removed_files",
    "flat_sibling_resolve_candidate_path",
    "ALLOWED_IMPORT_ALIASES",
    "PrivateImportFinding",
    "allowed_import_alias",
    "import_alias_full_name",
    "import_alias_replacement",
    "imported_modules",
    "is_private_module_segment",
    "module_path_from_python_file",
    "patch_added_source",
    "private_module_segments",
    "PythonPrivateImportChainRule",
    "PythonImportAliasRule",
    "PythonImportFanoutRule",
]
from ._source_parse import (
    first_significant_line,
    is_full_module_candidate,
    line_count,
    looks_like_indented_fragment,
    parse_health_failure,
    parse_strict,
    parsed_classes,
    parsed_functions,
    parsed_nodes,
    python_ast_rule_is_disabled,
    resolve_python_path,
)
from .module import PythonModuleSizeRule, ModuleSizeFinding
from .module import (
    OVERSIZED_SPLIT_PLANS,
    module_split_scenario,
    oversized_module_split_guidance,
)
from .module import (
    dedupe_sources,
    is_authored_python_path,
    is_line_count_camouflage,
    post_python_structural_sources,
    pre_python_camouflage_sources,
    pre_python_structural_sources,
    project_multiedit_sources,
    project_replacement,
    project_top_level_edit,
    python_structural_sources,
    read_python_source,
)
from ._ast_health import PythonAstHealthRule
from ._broad_silent import (
    PythonBroadExceptLoggerRule,
    PythonSilentExceptRule,
    is_broad_exception,
    is_empty_default_return,
    is_logger_call,
)
from ._boundary_helpers import (
    BOUNDARY_LOG_METHODS,
    BOUNDARY_LOG_NAMES,
    BoundaryFunction,
    EVENT_CALL_NAMES,
    EVENT_NAME_MARKERS,
    EVENT_PATH_PARTS,
    HTTP_BOUNDARY_METHODS,
    PACKAGE_BOUNDARY_CLASS_SUFFIXES,
    PACKAGE_BOUNDARY_NAME_PARTS,
    PACKAGE_BOUNDARY_PATH_PARTS,
    attribute_chain_parts,
    boundary_kind_for_function,
    called_name,
    class_name_has_package_boundary_signal,
    contains_event_boundary_call,
    contains_package_boundary_call,
    function_name_has_event_signal,
    has_boundary_log_call,
    is_test_module_path,
    iter_public_boundary_functions,
    path_parts,
)
from ._boundary_rule import PythonBoundaryLoggingRule
from ._method_style import (
    PythonDeepNestingRule,
    PythonLongLineRule,
    PythonLongMethodRule,
    PythonLongParameterRule,
)
from ..feature_envy import PythonFeatureEnvyRule
from ._wrapper_god import (
    PythonGodClassRule,
    PythonThinWrapperRule,
    is_exempt_cast_wrapper,
    is_exempt_test_helper_wrapper,
    is_test_helper_path,
    is_wrapper_candidate,
    thin_wrapper_attribute_name,
    thin_wrapper_call_root_name,
    thin_wrapper_call_target_name,
    thin_wrapper_extract_single_call,
    thin_wrapper_has_self_or_cls_receiver,
)
from ._complexity_dead import (
    PythonCyclomaticComplexityRule,
    PythonDeadCodeRule,
    CC_BRANCH_TYPES,
)
from ._flat_siblings import (
    PythonFlatFileSiblingsRule,
    FlatSiblingFindingInput,
    flat_sibling_patch_added_and_removed_paths,
    flat_sibling_patch_blob,
    flat_sibling_projected_removed_files,
    flat_sibling_resolve_candidate_path,
)
from .imports import (
    ALLOWED_IMPORT_ALIASES,
    PrivateImportFinding,
    allowed_import_alias,
    import_alias_full_name,
    import_alias_replacement,
    imported_modules,
    is_private_module_segment,
    module_path_from_python_file,
    patch_added_source,
    private_module_segments,
)
from .private_imports import PythonPrivateImportChainRule
from .imports import PythonImportAliasRule, PythonImportFanoutRule
from .imports import alias_rule, fanout_rule, helpers
from .module.size import guidance, projection, sources


sys.modules.update(
    {
        f"{__name__}._import_alias_rule": alias_rule,
        f"{__name__}._import_fanout_rule": fanout_rule,
        f"{__name__}._import_helpers": helpers,
        f"{__name__}._module_size_guidance": guidance,
        f"{__name__}._module_size_projection": projection,
        f"{__name__}._module_size_sources": sources,
    }
)
