"""Compatibility facade for the former ``duplicates.py`` module."""

from __future__ import annotations

__all__ = [
    "ASTNodeT",
    "BUILTINS",
    "CONSTANT_TYPE_MAP",
    "FUNC_TYPES",
    "K",
    "Normalizer",
    "SKIP_DECORATORS",
    "canonical_alias",
    "canonical_import_stmt",
    "canonicalize_import_block",
    "emit_group_violations",
    "end_lineno",
    "has_skip_decorator",
    "import_section",
    "is_clone_candidate",
    "is_docstring_node",
    "is_future_import",
    "is_import_stmt",
    "normalize_ast",
    "skip_docstring",
    "structure_hash",
    "detect_semantic_clones",
    "collect_literals",
    "constant_location",
    "is_semantic_string_literal",
    "magic_number_violation",
    "string_literal_metadata",
    "string_literal_violation",
    "detect_repeated_literals",
    "MIN_BLOCK_SIZE",
    "collect_block_windows",
    "extract_call_sequence",
    "detect_duplicate_call_sequences",
    "detect_repeated_blocks",
]
from ._semantic import (
    ASTNodeT,
    BUILTINS,
    CONSTANT_TYPE_MAP,
    FUNC_TYPES,
    K,
    Normalizer,
    SKIP_DECORATORS,
    canonical_alias,
    canonical_import_stmt,
    canonicalize_import_block,
    emit_group_violations,
    end_lineno,
    has_skip_decorator,
    import_section,
    is_clone_candidate,
    is_docstring_node,
    is_future_import,
    is_import_stmt,
    normalize_ast,
    skip_docstring,
    structure_hash,
    detect_semantic_clones,
)
from ._literals import (
    collect_literals,
    constant_location,
    is_semantic_string_literal,
    magic_number_violation,
    string_literal_metadata,
    string_literal_violation,
    detect_repeated_literals,
)
from ._blocks import (
    MIN_BLOCK_SIZE,
    collect_block_windows,
    extract_call_sequence,
    detect_duplicate_call_sequences,
    detect_repeated_blocks,
)
