"""Builtin names ignored during semantic clone normalization."""

from __future__ import annotations

BUILTINS = frozenset(
    {
        "len",
        "range",
        "print",
        "str",
        "int",
        "float",
        "bool",
        "list",
        "dict",
        "set",
        "tuple",
        "type",
        "isinstance",
        "issubclass",
        "hasattr",
        "getattr",
        "setattr",
        "delattr",
        "super",
        "property",
        "staticmethod",
        "classmethod",
        "enumerate",
        "zip",
        "map",
        "filter",
        "sorted",
        "reversed",
        "min",
        "max",
        "sum",
        "any",
        "all",
        "abs",
        "round",
        "repr",
        "hash",
        "id",
        "callable",
        "iter",
        "next",
        "open",
        "ValueError",
        "TypeError",
        "KeyError",
        "AttributeError",
        "RuntimeError",
        "NotImplementedError",
        "StopIteration",
        "Exception",
        "True",
        "False",
        "None",
    }
)

SKIP_DECORATORS = frozenset({"abstractmethod", "overload", "property"})
